spring:
  application:
    name: farm-collector-api
  datasource:
    url: jdbc:mysql://localhost:3306/farm-collector-db?createDatabaseIfNotExist=true
    username: root
    password: Danvi@02
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    flyway:
      baseline-on-migrate: true


