server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**
          filters:
            - name: AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: AuthenticationFilter