spring:
  data:
    mongodb:
      uri: mongodb+srv://danvisrinivas:danvisilpa@hungersaviour.efr4kgm.mongodb.net/?retryWrites=true&w=majority
      database: orders
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:19092"
        - "localhost:29092"
        - "localhost:39092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer